[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "braillebase"
version = "0.0.13"
description = "A complete and extensible Unicode Braille processing library."
authors = [
    { name = "Nagao Yuji" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.6"
keywords = ["braille", "unicode", "accessibility", "API", "binary", "blind", "education"]

dependencies = [
    "brailletable>=1.0.1"
]

[project.urls]
Homepage = "https://github.com/DukaCrazy/braillebase"
Documentation = "https://github.com/DukaCrazy/braillebase"
Source = "https://github.com/DukaCrazy/braillebase"
